
bool SendTextMessage(char* name, char *Buffer, int blen);
bool SendTextMessage(int hwnd, char *Buffer, int blen);

int __stdcall ImageBase(void);
void __stdcall Jump      (int addr)  ; 
void __stdcall Refresh   (void)      ; 
int  __stdcall ScreenEA  (void)      ; 
int  __stdcall NumFuncs  (void)      ; 
void __stdcall RemvName  (int addr)  ; 
void __stdcall Setname(int addr, const char* name); 
//void __stdcall AddComment(char *cmt, char color); generate_big_comment(cmt, color);}
void __stdcall AddProgramComment(char *cmt); 
void __stdcall AddCodeXRef(int start, int end); 
void __stdcall DelCodeXRef(int start, int end); 
void __stdcall AddDataXRef(int start, int end); 
void __stdcall DelDataXRef(int start, int end); 
void __stdcall MessageUI(char *m);
void __stdcall PatchByte(int addr, char val);
void __stdcall PatchWord(int addr, int val); 
void __stdcall DelFunc(int addr);
int  __stdcall FuncIndex(int addr);
void __stdcall SelBounds( ulong* selStart, ulong* selEnd); 
void __stdcall FuncName(int addr, char *buf, size_t bufsize); 
int  __stdcall GetBytes(int offset, void *buf, int length);
void __stdcall Undefine(int offset); 
char __stdcall OriginalByte(int offset);
void __stdcall SetComment(int offset, char* comm);
void __stdcall GetComment(int offset, char* buf, int bufSize);
int __stdcall ProcessState(void);
int __stdcall FilePath(char *buf, int bufsize);
int __stdcall RootFileName(char *buf, int bufsize);
void __stdcall HideEA(int offset); 
void __stdcall ShowEA(int offset); 
int __stdcall NextAddr(int offset);
int __stdcall PrevAddr(int offset);
void __stdcall AnalyzeArea(int startat, int endat);
void __stdcall GetName(int offset, char* buf, int bufsize);
void __stdcall MakeCode(int offset);
int __stdcall FunctionStart(int n);
int __stdcall FunctionEnd(int n);
int __stdcall FuncArgSize(int index);
int __stdcall FuncColor(int index);
int __stdcall GetAsm(int addr, char* buf, int bufLen);
int __stdcall FirstCodeFrom(int ea);
int __stdcall FirstCodeTo(int ea);
int __stdcall NextCodeTo(int ea);
int __stdcall NextCodeFrom(int ea);
int __stdcall ImageBase(void);
int __stdcall GetRefsTo(int offset, int hwnd);
int __stdcall GetRefsFrom(int offset, int hwnd);