VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "CIdaScriptCmd"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public WithEvents ws As Winsock
Attribute ws.VB_VarHelpID = -1
Public WithEvents tmr As Timer
Attribute tmr.VB_VarHelpID = -1


Function SendBlockingCmd(cmd As String) As String
    
End Function

Function SendBlindCommand(cmd As String) As String

End Function

